#!/usr/bin/env ruby

if ARGV[0] && ARGV[1]
  require "bundler/setup"
  require "eml_to_pdf"
  EmlToPdf.convert(ARGV[0], ARGV[1])
elsif ARGV[0] && ARGV[1] && ARGV[2]
  require "bundler/setup"
  require "eml_to_pdf"
  EmlToPdf.convert_all(ARGV[0], ARGV[2])
else
  puts %{Please provide an input as well as an output path\nExample: emltopdf test-email.eml output.pdf}
end
