#!/usr/bin/env ruby
# TODO: use this to convert whole folders
# Dir["test/fixtures/emails/*.eml"].each do |test_file|
#   puts "> converting #{test_file}"
#   begin
#     EmlToPdf.convert(test_file, "#{test_file[0..-5]}_output.pdf")
#   rescue NoMethodError => e
#     puts e.message
#   end
# end

if ARGV[0] && ARGV[1]
  require "bundler/setup"
  require "eml_to_pdf"
  EmlToPdf.convert(ARGV[0], ARGV[1])
else
  puts %{Please provide an input as well as an output path\nExample: emltopdf test-email.eml output.pdf}
end
